export enum AUTH {
  AUTHORIZATION = 'AUTHORIZATION',
  WELCOME = 'WELCOME',
  PUBLIC_OFFER = 'PUBLIC_OFFER',
  REGISTRATION = 'REGISTRATION',
}
export enum MAIN {
  HOME = 'HOME',
  CALENDAR_SETTING = 'CALENDAR_SETTING',
  NOTIFICATIONS = 'NOTIFICATIONS',
}
export enum DRAWER {
  DRAWER = 'DRAWER',
}
export const ROUTES = {
  AUTH,
  MAIN,
  DRAWER,
} as const;
