export enum AUTH {
  AUTHORIZATION = 'AUTHORIZATION',
  WELCOME = 'WELCOME',
  PUBLIC_OFFER = 'PUBLIC_OFFER',
  REGISTRATION = 'REGISTRATION',
}
export enum MAIN {
  HOME = 'HOME',
  CALENDAR_SETTING = 'CALENDAR_SETTING',
  NOTIFICATIONS = 'NOTIFICATIONS',
  CREATE_TEST = 'CREATE_TEST',
}
export enum DRAWER {
  DRAWER = 'DRAWER',
  SETTING = 'SETTING',
  THEMATIC_PLANE = 'THEMATIC_PLANE',
  TESTING = 'TESTING',
  SUPPORT = 'SUPPORT',
  STATISTIC = 'STATISTIC',
  PROGRAM = 'PROGRAM',
  PAYMENT = 'PAYMENT',
  ELECTRONIC_RESOURCES = 'ELECTRONIC_RESOURCES',
}
export const ROUTES = {
  AUTH,
  MAIN,
  DRAWER,
} as const;
